/*
 *  Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  See the NOTICE file distributed with
 *  this work for additional information regarding copyright ownership.
 *  The ASF licenses this file to You under the Apache License, Version 2.0
 *  (the "License"); you may not use this file except in compliance with
 *  the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * @author Pavel Dolgov
 */

/* DO NOT EDIT THIS FILE - it is based on Win32 headers and has been generated by nativebridge tool.*/

#include <jni.h>
#include "nativelib_common.h"

#ifndef _Included_org_apache_harmony_awt_nativebridge_windows_Win32
#define _Included_org_apache_harmony_awt_nativebridge_windows_Win32

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_init (JNIEnv *, jclass);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_FillRect(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_LineTo(JNIEnv *, jobject, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetWindowLongW(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_PeekMessageW(JNIEnv *, jobject, jlong, jlong, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_BitBlt(JNIEnv *, jobject, jlong, jint, jint, jint, jint, jlong, jint, jint, jint);
JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall0(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetSaveFileNameW(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreateCaret(JNIEnv *, jobject, jlong, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ImmDestroyContext(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ImmGetCompositionStringW(JNIEnv *, jobject, jlong, jint, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetSystemMetrics(JNIEnv *, jobject, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetForegroundWindow(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SendMessageW(JNIEnv *, jobject, jlong, jint, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetThemeSysFont(JNIEnv *, jobject, jlong, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SystemParametersInfoW(JNIEnv *, jobject, jint, jint, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetCaretBlinkTime(JNIEnv *, jobject);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreateDCW(JNIEnv *, jobject, jlong, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_Arc(JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ImmReleaseContext(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_PolyPolygon(JNIEnv *, jobject, jlong, jlong, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreatePen(JNIEnv *, jobject, jint, jint, jint);

JNIEXPORT jshort  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetKeyState(JNIEnv *, jobject, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreateIconIndirect(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_RoundRect(JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ExtCreateRegion(JNIEnv *, jobject, jlong, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetThemeSysInt(JNIEnv *, jobject, jlong, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_TrackMouseEvent(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreateWindowExW(JNIEnv *, jobject, jint, jlong, jlong, jint, jint, jint, jint, jint, jlong, jlong, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetClipboardViewer(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_Ellipse(JNIEnv *, jobject, jlong, jint, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetLastError(JNIEnv *, jobject);

JNIEXPORT void  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SHGetSettings(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ImmAssociateContext(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ImmGetContext(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetPixel(JNIEnv *, jobject, jlong, jint, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetDC(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetBkMode(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetStockObject(JNIEnv *, jobject, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ValidateRgn(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT void  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_keybd_1event(JNIEnv *, jobject, jbyte, jbyte, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_DrawThemeBackground(JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetMonitorInfoW(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetCurrentThreadId(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_DeleteDC(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SHGetFileInfoW(JNIEnv *, jobject, jlong, jint, jlong, jint, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_DispatchMessageW(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_PostThreadMessageW(JNIEnv *, jobject, jint, jint, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetSysColor(JNIEnv *, jobject, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetSystemMenu(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetPixelFormat(JNIEnv *, jobject, jlong, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetCursorPos(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_PatBlt(JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetCursor(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_AppendMenuW(JNIEnv *, jobject, jlong, jint, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetWindowPlacement(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ActivateKeyboardLayout(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CommDlgExtendedError(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GlobalUnlock(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetROP2(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SHBindToParent(JNIEnv *, jobject, jlong, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_InSendMessageEx(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetLocaleInfoW(JNIEnv *, jobject, jint, jint, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall1(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall2(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall3(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall4(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall5(JNIEnv *, jobject, jlong, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall6(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall7(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall8(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall9(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall10(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall11(JNIEnv *, jobject, jlong, jlong, jlong, jint, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall12(JNIEnv *, jobject, jlong, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall13(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall14(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall15(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall16(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall17(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall18(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall19(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall20(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall21(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall22(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall23(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall24(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall25(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall26(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall27(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall28(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall29(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SHGetDataFromIDListW(JNIEnv *, jobject, jlong, jlong, jint, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ScreenToClient(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetParent(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetFocus(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_DescribePixelFormat(JNIEnv *, jobject, jlong, jint, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetTextColor(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_MonitorFromWindow(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetDIBits(JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_FormatMessageW(JNIEnv *, jobject, jint, jlong, jint, jint, jlong, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SHGetDesktopFolder(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ImmSetCompositionWindow(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SendInput(JNIEnv *, jobject, jint, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_DeleteObject(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ImmIsIME(JNIEnv *, jobject, jlong);
JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall30(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong);

JNIEXPORT jshort  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_RegisterClassExW(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetWindowDC(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_RegisterClipboardFormatW(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetFocus(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_EnumClipboardFormats(JNIEnv *, jobject, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreateRectRgn(JNIEnv *, jobject, jint, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_DestroyCursor(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetCurrentThemeName(JNIEnv *, jobject, jlong, jint, jlong, jint, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetClipboardData(JNIEnv *, jobject, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_MoveToEx(JNIEnv *, jobject, jlong, jint, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ImmNotifyIME(JNIEnv *, jobject, jlong, jint, jint, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_WindowFromPoint(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetCapture(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_DestroyCaret(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetWindowTextW(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_DrawFocusRect(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreateBrushIndirect(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_MapVirtualKeyW(JNIEnv *, jobject, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetRgnBox(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetActiveWindow(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_WideCharToMultiByte(JNIEnv *, jobject, jint, jint, jlong, jint, jlong, jint, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_IsThemeActive(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetThemeSysColor(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GlobalSize(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_FillRgn(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_DrawFrameControl(JNIEnv *, jobject, jlong, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_EmptyClipboard(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_DestroyWindow(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CloseThemeData(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_TextOutW(JNIEnv *, jobject, jlong, jint, jint, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetCaretPos(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetThemeSysSize(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SelectClipRgn(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SHGetFolderLocation(JNIEnv *, jobject, jlong, jint, jlong, jint, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ImmCreateContext(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CLSIDFromString(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_StrRetToBufW(JNIEnv *, jobject, jlong, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetPolyFillMode(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_LocalFree(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreateCompatibleDC(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreateCompatibleBitmap(JNIEnv *, jobject, jlong, jint, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_DefWindowProcW(JNIEnv *, jobject, jlong, jint, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CloseClipboard(JNIEnv *, jobject);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetActiveWindow(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetDeviceCaps(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreatePatternBrush(JNIEnv *, jobject, jlong);

JNIEXPORT void  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_mouse_1event(JNIEnv *, jobject, jint, jint, jint, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_EnumDisplayDevicesW(JNIEnv *, jobject, jlong, jint, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetWindowLongW(JNIEnv *, jobject, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_Polygon(JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetUpdateRgn(JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_Pie(JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetClipboardOwner(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ShowWindow(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_MapWindowPoints(JNIEnv *, jobject, jlong, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ChoosePixelFormat(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_PolyPolyline(JNIEnv *, jobject, jlong, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetRandomRgn(JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ExtCreatePen(JNIEnv *, jobject, jint, jint, jlong, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ChangeDisplaySettingsExW(JNIEnv *, jobject, jlong, jlong, jlong, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetRegionData(JNIEnv *, jobject, jlong, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_InflateRect(JNIEnv *, jobject, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetBkColor(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetAncestor(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetThemeSysBool(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_TranslateMessage(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreateSolidBrush(JNIEnv *, jobject, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_OpenThemeData(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetWindowPlacement(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ReleaseCapture(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_MultiByteToWideChar(JNIEnv *, jobject, jint, jint, jlong, jint, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_PlaySoundW(JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetObjectW(JNIEnv *, jobject, jlong, jint, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_LoadCursorW(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_EnableTheming(JNIEnv *, jobject, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_IsIconic(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_EnableWindow(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_PostMessageW(JNIEnv *, jobject, jlong, jint, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GlobalLock(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ReleaseDC(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetKeyboardLayoutList(JNIEnv *, jobject, jint, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SelectObject(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetKeyboardLayout(JNIEnv *, jobject, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetWindowRect(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_DrawEdge(JNIEnv *, jobject, jlong, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetMessageW(JNIEnv *, jobject, jlong, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetPixelFormat(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetClipboardData(JNIEnv *, jobject, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_MulDiv(JNIEnv *, jobject, jint, jint, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreateBitmap(JNIEnv *, jobject, jint, jint, jint, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetClipboardFormatNameW(JNIEnv *, jobject, jint, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetWindowPos(JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ImmSetOpenStatus(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetCaretPos(JNIEnv *, jobject, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetOpenFileNameW(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_CreateDIBSection(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_SetBkMode(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_Rectangle(JNIEnv *, jobject, jlong, jint, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetDoubleClickTime(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GetClientRect(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_UpdateWindow(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_GlobalAlloc(JNIEnv *, jobject, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_ChangeClipboardChain(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_OpenClipboard(JNIEnv *, jobject, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall31(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall32(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall33(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall34(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall35(JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall36(JNIEnv *, jobject, jlong, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall37(JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall38(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall39(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall40(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall41(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall42(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall43(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall44(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall45(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall46(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall47(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall48(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall49(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall50(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall51(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall52(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall53(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall54(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall55(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall56(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall57(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall58(JNIEnv *, jobject, jlong, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall59(JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall60(JNIEnv *, jobject, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall61(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall62(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall63(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall64(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall65(JNIEnv *, jobject, jlong, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall66(JNIEnv *, jobject, jlong, jlong, jlong, jint, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall67(JNIEnv *, jobject, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall68(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall69(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall70(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall71(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall72(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall73(JNIEnv *, jobject, jlong, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall74(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall75(JNIEnv *, jobject, jlong, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall76(JNIEnv *, jobject, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall77(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall78(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall79(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall80(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall81(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall82(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall83(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall84(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall85(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall86(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall87(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall88(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall89(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall90(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall91(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall92(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall93(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall94(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall95(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall96(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall97(JNIEnv *, jobject, jlong, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall98(JNIEnv *, jobject, jlong, jlong, jint, jint, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall99(JNIEnv *, jobject, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall100(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall101(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall102(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall103(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall104(JNIEnv *, jobject, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall105(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall106(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall107(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall108(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall109(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall110(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall111(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall112(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall113(JNIEnv *, jobject, jlong, jlong, jlong, jint, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall114(JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall115(JNIEnv *, jobject, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall116(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall117(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall118(JNIEnv *, jobject, jlong, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall119(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall120(JNIEnv *, jobject, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall121(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall122(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall123(JNIEnv *, jobject, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall124(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall125(JNIEnv *, jobject, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall126(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall127(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall128(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall129(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall130(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall131(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall132(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall133(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall134(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall135(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall136(JNIEnv *, jobject, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall137(JNIEnv *, jobject, jlong, jlong, jint, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall138(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall139(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall140(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall141(JNIEnv *, jobject, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall142(JNIEnv *, jobject, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall143(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall144(JNIEnv *, jobject, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall145(JNIEnv *, jobject, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall146(JNIEnv *, jobject, jlong, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall147(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall148(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall149(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall150(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall151(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall152(JNIEnv *, jobject, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall153(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall154(JNIEnv *, jobject, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall155(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall156(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall157(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall158(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall159(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall160(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall161(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall162(JNIEnv *, jobject, jlong, jlong, jlong, jint, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall163(JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall164(JNIEnv *, jobject, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall165(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall166(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall167(JNIEnv *, jobject, jlong, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall168(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall169(JNIEnv *, jobject, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall170(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall171(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall172(JNIEnv *, jobject, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall173(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall174(JNIEnv *, jobject, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall175(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall176(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall177(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall178(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall179(JNIEnv *, jobject, jlong, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall180(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall181(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall182(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall183(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall184(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall185(JNIEnv *, jobject, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall186(JNIEnv *, jobject, jlong, jlong, jint, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall187(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall188(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall189(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jint, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall190(JNIEnv *, jobject, jlong, jlong, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_windows_Win32_proxycall191(JNIEnv *, jobject, jlong, jlong, jint, jlong);


#ifdef __cplusplus
}
#endif
#endif
