/*
 *  Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  See the NOTICE file distributed with
 *  this work for additional information regarding copyright ownership.
 *  The ASF licenses this file to You under the Apache License, Version 2.0
 *  (the "License"); you may not use this file except in compliance with
 *  the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * @author Igor V. Stolyarov
 */
/*
 * THE FILE HAS BEEN AUTOGENERATED BY INTEL IJH TOOL.
 * Please be aware that all changes made to this file manually
 * will be overwritten by the tool if it runs again.
 */

#include <jni.h>


/* Header for class org.apache.harmony.awt.gl.linux.XSurface */

#ifndef _ORG_APACHE_HARMONY_AWT_GL_LINUX_PIXMAPSURFACE
#define _ORG_APACHE_HARMONY_AWT_GL_LINUX_PIXMAPSURFACE

#ifdef __cplusplus
extern "C" {
#endif

/* Native methods */


/*
 * Method: org.apache.harmony.awt.gl.linux.PixmapSurface.createSurfData(JJJII)J
 */
JNIEXPORT jlong JNICALL 
Java_org_apache_harmony_awt_gl_linux_PixmapSurface_createSurfData(JNIEnv *, jobject, 
    jlong, jlong, jlong, jint, jint);

/*
 * Method: org.apache.harmony.awt.gl.linux.PixmapSurface.dispose(J)V
 */
JNIEXPORT void JNICALL 
Java_org_apache_harmony_awt_gl_linux_PixmapSurface_dispose(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif

#endif /* _ORG_APACHE_HARMONY_AWT_GL_LINUX_PIXMAPSURFACE */
