/*
 *  Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  See the NOTICE file distributed with
 *  this work for additional information regarding copyright ownership.
 *  The ASF licenses this file to You under the Apache License, Version 2.0
 *  (the "License"); you may not use this file except in compliance with
 *  the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * @author Alexey A. Petrenko
 */
/*
 * THE FILE HAS BEEN AUTOGENERATED BY INTEL IJH TOOL.
 * Please be aware that all changes made to this file manually
 * will be overwritten by the tool if it runs again.
 */

#include <jni.h>


/* Header for class java.awt.geom.PathIterator */

#ifndef _JAVA_AWT_GEOM_PATHITERATOR_H
#define _JAVA_AWT_GEOM_PATHITERATOR_H

#ifdef __cplusplus
extern "C" {
#endif


/* Static final fields */

#undef java_awt_geom_PathIterator_WIND_EVEN_ODD
#define java_awt_geom_PathIterator_WIND_EVEN_ODD 0L

#undef java_awt_geom_PathIterator_WIND_NON_ZERO
#define java_awt_geom_PathIterator_WIND_NON_ZERO 1L

#undef java_awt_geom_PathIterator_SEG_MOVETO
#define java_awt_geom_PathIterator_SEG_MOVETO 0L

#undef java_awt_geom_PathIterator_SEG_LINETO
#define java_awt_geom_PathIterator_SEG_LINETO 1L

#undef java_awt_geom_PathIterator_SEG_QUADTO
#define java_awt_geom_PathIterator_SEG_QUADTO 2L

#undef java_awt_geom_PathIterator_SEG_CUBICTO
#define java_awt_geom_PathIterator_SEG_CUBICTO 3L

#undef java_awt_geom_PathIterator_SEG_CLOSE
#define java_awt_geom_PathIterator_SEG_CLOSE 4L


#ifdef __cplusplus
}
#endif

#endif /* _JAVA_AWT_GEOM_PATHITERATOR_H */

