/*
 * RMI stub class
 * for class org.apache.harmony.rmi.activation.Rmid
 * Compatible with stub protocol version 1.1/1.2
 *
 * Generated by DRL RMI Compiler (rmic).
 *
 * DO NOT EDIT!!!
 * Contents subject to change without notice!
 */
package org.apache.harmony.rmi.activation;

import org.apache.harmony.rmi.internal.nls.Messages;


public final class Rmid_Stub extends java.rmi.server.RemoteStub
        implements java.rmi.activation.ActivationSystem, java.rmi.activation.ActivationMonitor, java.rmi.activation.Activator, java.rmi.Remote {

    private static final long serialVersionUID = 2;

    private static final long interfaceHash = 8470858815147946311L;

    private static boolean useNewInvoke;

    private static final java.rmi.server.Operation[] operations = {
        new java.rmi.server.Operation("java.rmi.MarshalledObject activate(java.rmi.activation.ActivationID, boolean)"), //$NON-NLS-1$
        new java.rmi.server.Operation("java.rmi.activation.ActivationMonitor activeGroup(java.rmi.activation.ActivationGroupID, java.rmi.activation.ActivationInstantiator, long)"), //$NON-NLS-1$
        new java.rmi.server.Operation("void activeObject(java.rmi.activation.ActivationID, java.rmi.MarshalledObject)"), //$NON-NLS-1$
        new java.rmi.server.Operation("java.rmi.activation.ActivationDesc getActivationDesc(java.rmi.activation.ActivationID)"), //$NON-NLS-1$
        new java.rmi.server.Operation("java.rmi.activation.ActivationGroupDesc getActivationGroupDesc(java.rmi.activation.ActivationGroupID)"), //$NON-NLS-1$
        new java.rmi.server.Operation("void inactiveGroup(java.rmi.activation.ActivationGroupID, long)"), //$NON-NLS-1$
        new java.rmi.server.Operation("void inactiveObject(java.rmi.activation.ActivationID)"), //$NON-NLS-1$
        new java.rmi.server.Operation("java.rmi.activation.ActivationGroupID registerGroup(java.rmi.activation.ActivationGroupDesc)"), //$NON-NLS-1$
        new java.rmi.server.Operation("java.rmi.activation.ActivationID registerObject(java.rmi.activation.ActivationDesc)"), //$NON-NLS-1$
        new java.rmi.server.Operation("java.rmi.activation.ActivationDesc setActivationDesc(java.rmi.activation.ActivationID, java.rmi.activation.ActivationDesc)"), //$NON-NLS-1$
        new java.rmi.server.Operation("java.rmi.activation.ActivationGroupDesc setActivationGroupDesc(java.rmi.activation.ActivationGroupID, java.rmi.activation.ActivationGroupDesc)"), //$NON-NLS-1$
        new java.rmi.server.Operation("void shutdown()"), //$NON-NLS-1$
        new java.rmi.server.Operation("void unregisterGroup(java.rmi.activation.ActivationGroupID)"), //$NON-NLS-1$
        new java.rmi.server.Operation("void unregisterObject(java.rmi.activation.ActivationID)") //$NON-NLS-1$
    };

    private static java.lang.reflect.Method $method_activate_0;
    private static java.lang.reflect.Method $method_activeGroup_1;
    private static java.lang.reflect.Method $method_activeObject_2;
    private static java.lang.reflect.Method $method_getActivationDesc_3;
    private static java.lang.reflect.Method $method_getActivationGroupDesc_4;
    private static java.lang.reflect.Method $method_inactiveGroup_5;
    private static java.lang.reflect.Method $method_inactiveObject_6;
    private static java.lang.reflect.Method $method_registerGroup_7;
    private static java.lang.reflect.Method $method_registerObject_8;
    private static java.lang.reflect.Method $method_setActivationDesc_9;
    private static java.lang.reflect.Method $method_setActivationGroupDesc_10;
    private static java.lang.reflect.Method $method_shutdown_11;
    private static java.lang.reflect.Method $method_unregisterGroup_12;
    private static java.lang.reflect.Method $method_unregisterObject_13;

    static {
        try {
            java.rmi.server.RemoteRef.class.getMethod("invoke", new java.lang.Class[] {java.rmi.Remote.class, java.lang.reflect.Method.class, java.lang.Object[].class, long.class}); //$NON-NLS-1$

            $method_activate_0 = java.rmi.activation.Activator.class.getMethod("activate", new java.lang.Class[] {java.rmi.activation.ActivationID.class, boolean.class}); //$NON-NLS-1$
            $method_activeGroup_1 = java.rmi.activation.ActivationSystem.class.getMethod("activeGroup", new java.lang.Class[] {java.rmi.activation.ActivationGroupID.class, java.rmi.activation.ActivationInstantiator.class, long.class}); //$NON-NLS-1$
            $method_activeObject_2 = java.rmi.activation.ActivationMonitor.class.getMethod("activeObject", new java.lang.Class[] {java.rmi.activation.ActivationID.class, java.rmi.MarshalledObject.class}); //$NON-NLS-1$
            $method_getActivationDesc_3 = java.rmi.activation.ActivationSystem.class.getMethod("getActivationDesc", new java.lang.Class[] {java.rmi.activation.ActivationID.class}); //$NON-NLS-1$
            $method_getActivationGroupDesc_4 = java.rmi.activation.ActivationSystem.class.getMethod("getActivationGroupDesc", new java.lang.Class[] {java.rmi.activation.ActivationGroupID.class}); //$NON-NLS-1$
            $method_inactiveGroup_5 = java.rmi.activation.ActivationMonitor.class.getMethod("inactiveGroup", new java.lang.Class[] {java.rmi.activation.ActivationGroupID.class, long.class}); //$NON-NLS-1$
            $method_inactiveObject_6 = java.rmi.activation.ActivationMonitor.class.getMethod("inactiveObject", new java.lang.Class[] {java.rmi.activation.ActivationID.class}); //$NON-NLS-1$
            $method_registerGroup_7 = java.rmi.activation.ActivationSystem.class.getMethod("registerGroup", new java.lang.Class[] {java.rmi.activation.ActivationGroupDesc.class}); //$NON-NLS-1$
            $method_registerObject_8 = java.rmi.activation.ActivationSystem.class.getMethod("registerObject", new java.lang.Class[] {java.rmi.activation.ActivationDesc.class}); //$NON-NLS-1$
            $method_setActivationDesc_9 = java.rmi.activation.ActivationSystem.class.getMethod("setActivationDesc", new java.lang.Class[] {java.rmi.activation.ActivationID.class, java.rmi.activation.ActivationDesc.class}); //$NON-NLS-1$
            $method_setActivationGroupDesc_10 = java.rmi.activation.ActivationSystem.class.getMethod("setActivationGroupDesc", new java.lang.Class[] {java.rmi.activation.ActivationGroupID.class, java.rmi.activation.ActivationGroupDesc.class}); //$NON-NLS-1$
            $method_shutdown_11 = java.rmi.activation.ActivationSystem.class.getMethod("shutdown", new java.lang.Class[] {}); //$NON-NLS-1$
            $method_unregisterGroup_12 = java.rmi.activation.ActivationSystem.class.getMethod("unregisterGroup", new java.lang.Class[] {java.rmi.activation.ActivationGroupID.class}); //$NON-NLS-1$
            $method_unregisterObject_13 = java.rmi.activation.ActivationSystem.class.getMethod("unregisterObject", new java.lang.Class[] {java.rmi.activation.ActivationID.class}); //$NON-NLS-1$

            useNewInvoke = true;
        } catch (java.lang.NoSuchMethodException e) {
            useNewInvoke = false;
        }
    }

    public Rmid_Stub() {
        super();
    }

    public Rmid_Stub(java.rmi.server.RemoteRef ref) {
        super(ref);
    }

    // Implementation of activate(ActivationID, boolean)
    public java.rmi.MarshalledObject activate(java.rmi.activation.ActivationID $param_ActivationID_1, boolean $param_boolean_2)
            throws java.rmi.activation.ActivationException, java.rmi.activation.UnknownObjectException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                java.lang.Object $result = ref.invoke(this, $method_activate_0, new java.lang.Object[] {$param_ActivationID_1, new java.lang.Boolean($param_boolean_2)}, -8767355154875805558L);
                return ((java.rmi.MarshalledObject) $result);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 0, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationID_1);
                    out.writeBoolean($param_boolean_2);
                } catch (java.io.IOException e) {
                    // rmi.26=Error marshalling arguments
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                java.rmi.MarshalledObject $result;

                try {
                    java.io.ObjectInput in = call.getInputStream();
                    $result = (java.rmi.MarshalledObject) in.readObject();
                } catch (java.io.IOException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } catch (java.lang.ClassNotFoundException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } finally {
                    ref.done(call);
                }

                return $result;
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.ActivationException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of activeGroup(ActivationGroupID, ActivationInstantiator, long)
    public java.rmi.activation.ActivationMonitor activeGroup(java.rmi.activation.ActivationGroupID $param_ActivationGroupID_1, java.rmi.activation.ActivationInstantiator $param_ActivationInstantiator_2, long $param_long_3)
            throws java.rmi.activation.UnknownGroupException, java.rmi.activation.ActivationException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                java.lang.Object $result = ref.invoke(this, $method_activeGroup_1, new java.lang.Object[] {$param_ActivationGroupID_1, $param_ActivationInstantiator_2, new java.lang.Long($param_long_3)}, -4575843150759415294L);
                return ((java.rmi.activation.ActivationMonitor) $result);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 1, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationGroupID_1);
                    out.writeObject($param_ActivationInstantiator_2);
                    out.writeLong($param_long_3);
                } catch (java.io.IOException e) {
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                java.rmi.activation.ActivationMonitor $result;

                try {
                    java.io.ObjectInput in = call.getInputStream();
                    $result = (java.rmi.activation.ActivationMonitor) in.readObject();
                } catch (java.io.IOException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } catch (java.lang.ClassNotFoundException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } finally {
                    ref.done(call);
                }

                return $result;
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.ActivationException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of activeObject(ActivationID, MarshalledObject)
    public void activeObject(java.rmi.activation.ActivationID $param_ActivationID_1, java.rmi.MarshalledObject $param_MarshalledObject_2)
            throws java.rmi.activation.UnknownObjectException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                ref.invoke(this, $method_activeObject_2, new java.lang.Object[] {$param_ActivationID_1, $param_MarshalledObject_2}, 2543984342209939736L);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 2, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationID_1);
                    out.writeObject($param_MarshalledObject_2);
                } catch (java.io.IOException e) {
                    // rmi.26=Error marshalling arguments
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                ref.done(call);
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.UnknownObjectException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of getActivationDesc(ActivationID)
    public java.rmi.activation.ActivationDesc getActivationDesc(java.rmi.activation.ActivationID $param_ActivationID_1)
            throws java.rmi.activation.ActivationException, java.rmi.activation.UnknownObjectException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                java.lang.Object $result = ref.invoke(this, $method_getActivationDesc_3, new java.lang.Object[] {$param_ActivationID_1}, 4830055440982622087L);
                return ((java.rmi.activation.ActivationDesc) $result);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 3, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationID_1);
                } catch (java.io.IOException e) {
                    // rmi.26=Error marshalling arguments
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                java.rmi.activation.ActivationDesc $result;

                try {
                    java.io.ObjectInput in = call.getInputStream();
                    $result = (java.rmi.activation.ActivationDesc) in.readObject();
                } catch (java.io.IOException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } catch (java.lang.ClassNotFoundException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } finally {
                    ref.done(call);
                }

                return $result;
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.ActivationException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of getActivationGroupDesc(ActivationGroupID)
    public java.rmi.activation.ActivationGroupDesc getActivationGroupDesc(java.rmi.activation.ActivationGroupID $param_ActivationGroupID_1)
            throws java.rmi.activation.ActivationException, java.rmi.activation.UnknownGroupException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                java.lang.Object $result = ref.invoke(this, $method_getActivationGroupDesc_4, new java.lang.Object[] {$param_ActivationGroupID_1}, -8701843806548736528L);
                return ((java.rmi.activation.ActivationGroupDesc) $result);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 4, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationGroupID_1);
                } catch (java.io.IOException e) {
                    // rmi.26=Error marshalling arguments
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                java.rmi.activation.ActivationGroupDesc $result;

                try {
                    java.io.ObjectInput in = call.getInputStream();
                    $result = (java.rmi.activation.ActivationGroupDesc) in.readObject();
                } catch (java.io.IOException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } catch (java.lang.ClassNotFoundException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } finally {
                    ref.done(call);
                }

                return $result;
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.ActivationException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of inactiveGroup(ActivationGroupID, long)
    public void inactiveGroup(java.rmi.activation.ActivationGroupID $param_ActivationGroupID_1, long $param_long_2)
            throws java.rmi.activation.UnknownGroupException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                ref.invoke(this, $method_inactiveGroup_5, new java.lang.Object[] {$param_ActivationGroupID_1, new java.lang.Long($param_long_2)}, -399287892768650944L);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 5, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationGroupID_1);
                    out.writeLong($param_long_2);
                } catch (java.io.IOException e) {
                    // rmi.26=Error marshalling arguments
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                ref.done(call);
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.UnknownGroupException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of inactiveObject(ActivationID)
    public void inactiveObject(java.rmi.activation.ActivationID $param_ActivationID_1)
            throws java.rmi.activation.UnknownObjectException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                ref.invoke(this, $method_inactiveObject_6, new java.lang.Object[] {$param_ActivationID_1}, -4165404120701281807L);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 6, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationID_1);
                } catch (java.io.IOException e) {
                    // rmi.26=Error marshalling arguments
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                ref.done(call);
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.UnknownObjectException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of registerGroup(ActivationGroupDesc)
    public java.rmi.activation.ActivationGroupID registerGroup(java.rmi.activation.ActivationGroupDesc $param_ActivationGroupDesc_1)
            throws java.rmi.activation.ActivationException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                java.lang.Object $result = ref.invoke(this, $method_registerGroup_7, new java.lang.Object[] {$param_ActivationGroupDesc_1}, 6921515268192657754L);
                return ((java.rmi.activation.ActivationGroupID) $result);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 7, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationGroupDesc_1);
                } catch (java.io.IOException e) {
                    // rmi.26=Error marshalling arguments
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                java.rmi.activation.ActivationGroupID $result;

                try {
                    java.io.ObjectInput in = call.getInputStream();
                    $result = (java.rmi.activation.ActivationGroupID) in.readObject();
                } catch (java.io.IOException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } catch (java.lang.ClassNotFoundException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } finally {
                    ref.done(call);
                }

                return $result;
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.ActivationException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of registerObject(ActivationDesc)
    public java.rmi.activation.ActivationID registerObject(java.rmi.activation.ActivationDesc $param_ActivationDesc_1)
            throws java.rmi.activation.ActivationException, java.rmi.activation.UnknownGroupException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                java.lang.Object $result = ref.invoke(this, $method_registerObject_8, new java.lang.Object[] {$param_ActivationDesc_1}, -3006759798994351347L);
                return ((java.rmi.activation.ActivationID) $result);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 8, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationDesc_1);
                } catch (java.io.IOException e) {
                    // rmi.26=Error marshalling arguments
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                java.rmi.activation.ActivationID $result;

                try {
                    java.io.ObjectInput in = call.getInputStream();
                    $result = (java.rmi.activation.ActivationID) in.readObject();
                } catch (java.io.IOException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } catch (java.lang.ClassNotFoundException e) {
                    //rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } finally {
                    ref.done(call);
                }

                return $result;
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.ActivationException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of setActivationDesc(ActivationID, ActivationDesc)
    public java.rmi.activation.ActivationDesc setActivationDesc(java.rmi.activation.ActivationID $param_ActivationID_1, java.rmi.activation.ActivationDesc $param_ActivationDesc_2)
            throws java.rmi.activation.ActivationException, java.rmi.activation.UnknownObjectException, java.rmi.activation.UnknownGroupException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                java.lang.Object $result = ref.invoke(this, $method_setActivationDesc_9, new java.lang.Object[] {$param_ActivationID_1, $param_ActivationDesc_2}, 7128043237057180796L);
                return ((java.rmi.activation.ActivationDesc) $result);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 9, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationID_1);
                    out.writeObject($param_ActivationDesc_2);
                } catch (java.io.IOException e) {
                    // rmi.26=Error marshalling arguments
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                java.rmi.activation.ActivationDesc $result;

                try {
                    java.io.ObjectInput in = call.getInputStream();
                    $result = (java.rmi.activation.ActivationDesc) in.readObject();
                } catch (java.io.IOException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } catch (java.lang.ClassNotFoundException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } finally {
                    ref.done(call);
                }

                return $result;
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.ActivationException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of setActivationGroupDesc(ActivationGroupID, ActivationGroupDesc)
    public java.rmi.activation.ActivationGroupDesc setActivationGroupDesc(java.rmi.activation.ActivationGroupID $param_ActivationGroupID_1, java.rmi.activation.ActivationGroupDesc $param_ActivationGroupDesc_2)
            throws java.rmi.activation.ActivationException, java.rmi.activation.UnknownGroupException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                java.lang.Object $result = ref.invoke(this, $method_setActivationGroupDesc_10, new java.lang.Object[] {$param_ActivationGroupID_1, $param_ActivationGroupDesc_2}, 1213918527826541191L);
                return ((java.rmi.activation.ActivationGroupDesc) $result);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 10, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationGroupID_1);
                    out.writeObject($param_ActivationGroupDesc_2);
                } catch (java.io.IOException e) {
                    // rmi.26=Error marshalling arguments
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                java.rmi.activation.ActivationGroupDesc $result;

                try {
                    java.io.ObjectInput in = call.getInputStream();
                    $result = (java.rmi.activation.ActivationGroupDesc) in.readObject();
                } catch (java.io.IOException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } catch (java.lang.ClassNotFoundException e) {
                    // rmi.27=Error unmarshalling return value
                    throw new java.rmi.UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
                } finally {
                    ref.done(call);
                }

                return $result;
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.ActivationException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of shutdown()
    public void shutdown()
            throws java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                ref.invoke(this, $method_shutdown_11, null, -7207851917985848402L);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 11, interfaceHash);

                ref.invoke(call);

                ref.done(call);
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of unregisterGroup(ActivationGroupID)
    public void unregisterGroup(java.rmi.activation.ActivationGroupID $param_ActivationGroupID_1)
            throws java.rmi.activation.ActivationException, java.rmi.activation.UnknownGroupException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                ref.invoke(this, $method_unregisterGroup_12, new java.lang.Object[] {$param_ActivationGroupID_1}, 3768097077835970701L);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 12, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationGroupID_1);
                } catch (java.io.IOException e) {
                    // rmi.26=Error marshalling arguments
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                ref.done(call);
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.ActivationException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of unregisterObject(ActivationID)
    public void unregisterObject(java.rmi.activation.ActivationID $param_ActivationID_1)
            throws java.rmi.activation.ActivationException, java.rmi.activation.UnknownObjectException, java.rmi.RemoteException {
        try {
            if (useNewInvoke) {
                ref.invoke(this, $method_unregisterObject_13, new java.lang.Object[] {$param_ActivationID_1}, -6843850585331411084L);
            } else {
                java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 13, interfaceHash);

                try {
                    java.io.ObjectOutput out = call.getOutputStream();
                    out.writeObject($param_ActivationID_1);
                } catch (java.io.IOException e) {
                    // rmi.26=Error marshalling arguments
                    throw new java.rmi.MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
                }

                ref.invoke(call);

                ref.done(call);
            }
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.rmi.activation.ActivationException e) {
            throw e;
        } catch (java.lang.Exception e) {
            // rmi.0C=Undeclared checked exception
            throw new java.rmi.UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }
}
