/*
 *  Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  See the NOTICE file distributed with
 *  this work for additional information regarding copyright ownership.
 *  The ASF licenses this file to You under the Apache License, Version 2.0
 *  (the "License"); you may not use this file except in compliance with
 *  the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * @author Pavel Dolgov
 */

/* DO NOT EDIT THIS FILE - it is based on X11 headers and was autogenerated by nativebridge tool */

#include <jni.h>
#include "nativelib_common.h"

#ifndef _Included_org_apache_harmony_awt_nativebridge_linux_X11
#define _Included_org_apache_harmony_awt_nativebridge_linux_X11

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_init (JNIEnv *, jclass);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_proxycall0(JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint, jlong, jint, jint, jint, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_proxycall1(JNIEnv *, jobject, jlong, jlong);
JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_proxycall2(JNIEnv *, jobject, jlong, jlong, jint, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_proxycall3(JNIEnv *, jobject, jlong, jlong, jint, jint, jlong);
JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_proxycall4(JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_proxycall5(JNIEnv *, jobject, jlong, jlong, jlong);
JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_proxycall6(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetSubImage(JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jlong, jint, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XAllocColor(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XLookupString(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetWMNormalHints(JNIEnv *, jobject, jlong, jlong, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XCreatePixmapCursor(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetInputFocus(JNIEnv *, jobject, jlong, jlong, jint, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XOpenDisplay(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGrabServer(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XCreateFontCursor(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XCreateImage(JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jlong, jint, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XRestackWindows(JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDefaultDepth(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XFree(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XMoveWindow(JNIEnv *, jobject, jlong, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XScreenCount(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDefaultRootWindow(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XResizeWindow(JNIEnv *, jobject, jlong, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XFillPolygon(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XTestFakeMotionEvent(JNIEnv *, jobject, jlong, jint, jint, jint, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XCreateGC(JNIEnv *, jobject, jlong, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XTestFakeKeyEvent(JNIEnv *, jobject, jlong, jint, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XCopyArea(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jint, jint, jint, jint, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XKeycodeToKeysym(JNIEnv *, jobject, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XImageByteOrder(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDefaultScreen(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XConvertSelection(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetSelectionOwner(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XFillRectangles(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetIconName(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDisplayWidthMM(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XMapWindow(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XParseColor(JNIEnv *, jobject, jlong, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XTestFakeButtonEvent(JNIEnv *, jobject, jlong, jint, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetWindowProperty(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jint, jlong, jlong, jlong, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XIconifyWindow(JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XAllocWMHints(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetRGBColormaps(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetVisualInfo(JNIEnv *, jobject, jlong, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetFunction(JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDestroyWindow(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XRootWindow(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XLowerWindow(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetAtomName(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSelectInput(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetImage(JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDrawRectangle(JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XUngrabPointer(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetForeground(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XMapRaised(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XAllPlanes(JNIEnv *, jobject);

JNIEXPORT jbyte  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XKeysymToKeycode(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XQueryPointer(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDisplayWidth(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDisplayHeightMM(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XChangeProperty(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jint, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XCheckTypedEvent(JNIEnv *, jobject, jlong, jint, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XPutImage(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jint, jint, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XmuLookupStandardColormap(JNIEnv *, jobject, jlong, jint, jlong, jint, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XStoreName(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XAllocStandardColormap(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetClipRectangles(JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XChangeWindowAttributes(JNIEnv *, jobject, jlong, jlong, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDisplayString(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetFillRule(JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XInitImage(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetDashes(JNIEnv *, jobject, jlong, jlong, jint, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetWMHints(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XPending(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XVisualIDFromVisual(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSendEvent(JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDrawLine(JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XCreatePixmap(JNIEnv *, jobject, jlong, jlong, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDefineCursor(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDrawLines(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jint);

JNIEXPORT void  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetWMNormalHints(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XTranslateCoordinates(JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetStandardProperties(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jint, jlong);

JNIEXPORT void  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_Xutf8SetWMProperties(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jint, jlong, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDefaultColormap(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XAllocSizeHints(JNIEnv *, jobject);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XFlush(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetWindowAttributes(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XFreePixmap(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetGeometry(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XQueryColors(JNIEnv *, jobject, jlong, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XQueryBestCursor(JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XNextEvent(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDefaultVisual(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XCreateWindow(JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XFreeGC(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XBitmapPad(JNIEnv *, jobject, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XCreateColormap(JNIEnv *, jobject, jlong, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetPointerMapping(JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetErrorHandler(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetTransientForHint(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XFreeCursor(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XFillRectangle(JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetWMProtocols(JNIEnv *, jobject, jlong, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XCloseDisplay(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XQueryTree(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetInputFocus(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XInternAtom(JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetClipOrigin(JNIEnv *, jobject, jlong, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XTestQueryExtension(JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XCreateSimpleWindow(JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XUngrabServer(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XFillArc(JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint, jint, jint, jint);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XScreenOfDisplay(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetClipMask(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XChangeGC(JNIEnv *, jobject, jlong, jlong, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XCreateBitmapFromData(JNIEnv *, jobject, jlong, jlong, jlong, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDeleteProperty(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGetWMHints(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XSetSelectionOwner(JNIEnv *, jobject, jlong, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDestroyImage(JNIEnv *, jobject, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDrawArc(JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint, jint, jint, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XGrabPointer(JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XDisplayHeight(JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XQueryColor(JNIEnv *, jobject, jlong, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XRaiseWindow(JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jint  JNICALL Java_org_apache_harmony_awt_nativebridge_linux_X11_XWithdrawWindow(JNIEnv *, jobject, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
