HYZLIB_0.1 {
	global :
		adler32;
		compress;
		crc32;
		deflate;
		deflateCopy;
		deflateEnd;
		deflateInit2_;
		deflateInit_;
		deflateParams;
		deflateReset;
		deflateSetDictionary;
		inflate;
		inflateEnd;
		inflateInit2_;
		inflateInit_;
		inflateReset;
		inflateSetDictionary;
		inflateSync;
		uncompress;
		zlibVersion;
		zError;
		inflateSyncPoint;
		get_crc_table;
		compress2;
	local : *;
};
