org/apache/harmony/awt/gl/linux/XGraphics2DRTest.java
java/awt/BasicStrokeTest.java
java/awt/geom/CubicCurve2DDoubleTest.java
java/awt/geom/CubicCurve2DFloatTest.java
java/awt/geom/CubicCurve2DTest.java
java/awt/geom/Line2DTest.java
java/awt/geom/Rectangle2DTest.java
java/awt/image/BufferedImageFilterTest.java
java/awt/KeyboardFocusManagerRTest.java
org/apache/harmony/awt/tests/nativebridge/PointerPointerTest.java
java/awt/font/TextLayoutTest.java
java/awt/font/TextMeasurerTest.java
java/awt/font/LineBreakMeasurerTest.java
java/awt/ButtonRTest.java
java/awt/KeyboardFocusManagerRTest.java

#HARMONY-4181
java/awt/geom/AreaTest.java

#HARMONY-4307
org/apache/harmony/awt/ListenerListTest.java
