javax/swing/JFileChooserTest.java
javax/swing/JFileChooserRTest.java
javax/swing/plaf/basic/BasicFileChooserUITest.java
javax/swing/plaf/basic/BasicListUITest.java
javax/swing/plaf/metal/MetalFileChooserUITest.java

javax/swing/Timer_MultithreadedTest.java
javax/swing/text/AbstractDocument_AbstractElement_MASNoLockTest.java

#HARMONY-3968
javax/swing/text/html/FormViewTest.java
#HARMONY-3969
javax/swing/text/html/HTMLEditorKitTest.java
