javax/swing/InputMapTest.java
javax/swing/JCheckBoxMenuItemTest.java
javax/swing/JFileChooserTest.java
javax/swing/LayoutFocusTraversalPolicyTest.java
javax/swing/SpringLayoutTest.java
javax/swing/plaf/basic/BasicCheckBoxMenuItemUITest.java
javax/swing/plaf/basic/BasicMenuItemUITest.java
javax/swing/plaf/basic/BasicMenuUITest.java
javax/swing/plaf/metal/MetalFileChooserUITest.java
javax/swing/plaf/metal/MetalIconFactoryTest.java

javax/swing/text/html/FormViewTest.java
javax/swing/text/html/HTMLEditorKitTest.java
javax/swing/text/WrappedPlainView_SimpleTest.java
