/*
 * RMI stub class
 * for class org.apache.harmony.rmi.activation.HelloImpl
 * Compatible with stub protocol version 1.2
 *
 * Generated by DRL RMI Compiler (rmic).
 *
 * DO NOT EDIT!!!
 * Contents subject to change without notice!
 */
package org.apache.harmony.rmi.tests.java.rmi.activation;


public final class HelloImpl_Stub extends java.rmi.server.RemoteStub
        implements org.apache.harmony.rmi.tests.java.rmi.activation.HelloI, java.rmi.Remote {

    private static final long serialVersionUID = 2;

    private static java.lang.reflect.Method $method_get_0;

    static {
        try {
            $method_get_0 = org.apache.harmony.rmi.tests.java.rmi.activation.HelloI.class.getMethod("get", new java.lang.Class[] {});
        } catch (java.lang.NoSuchMethodException e) {
            throw new java.lang.NoSuchMethodError(
                    "Stub class initialization failed: org.apache.harmony.rmi.tests.java.rmi.activation.HelloImpl_Stub");
        }
    }

    public HelloImpl_Stub(java.rmi.server.RemoteRef ref) {
        super(ref);
    }

    // Implementation of get()
    public java.lang.String get()
            throws java.rmi.RemoteException {
        try {
            java.lang.Object $result = ref.invoke(this, $method_get_0, null, 1118015571883637415L);
            return ((java.lang.String) $result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("Undeclared checked exception", e);
        }
    }
}
