HYJSSE_0.1 {
  global :
    Java_org_apache_harmony_xnet_provider_jsse_SSLParameters_initialiseDefaults;
    Java_org_apache_harmony_xnet_provider_jsse_SSLParameters_initialiseContext;
    Java_org_apache_harmony_xnet_provider_jsse_SSLParameters_setEnabledProtocolsImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLParameters_setClientAuthImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLParameters_setEnabledCipherSuitesImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLSessionImpl_initialiseSession;
    Java_org_apache_harmony_xnet_provider_jsse_SSLSessionImpl_getCipherNameImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLSessionImpl_getCreationTimeImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLSessionImpl_getPeerCertificatesImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLSocketImpl_initImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLSocketImpl_sslAcceptImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLSocketImpl_sslConnectImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLSocketImpl_writeAppDataImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLSocketImpl_readAppDataImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLSocketImpl_closeImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLEngineImpl_initImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLEngineImpl_initSSL;
    Java_org_apache_harmony_xnet_provider_jsse_SSLEngineImpl_initSSLEngine;
    Java_org_apache_harmony_xnet_provider_jsse_SSLEngineImpl_acceptImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLEngineImpl_connectImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLEngineImpl_wrapImpl;
    Java_org_apache_harmony_xnet_provider_jsse_SSLEngineImpl_unwrapImpl;
  local : *;
};
