/* 
 *  Licensed to the Apache Software Foundation (ASF) under one or more 
 *  contributor license agreements.  See the NOTICE file distributed with 
 *  this work for additional information regarding copyright ownership. 
 *  The ASF licenses this file to You under the Apache License, Version 2.0 
 *  (the "License"); you may not use this file except in compliance with 
 *  the License.  You may obtain a copy of the License at 
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0 
 * 
 *  Unless required by applicable law or agreed to in writing, software 
 *  distributed under the License is distributed on an "AS IS" BASIS, 
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 *  See the License for the specific language governing permissions and 
 *  limitations under the License. 
 */
/* Generated By:JavaCC: Do not edit this line. LdapUrlParserConstants.java */
package org.apache.harmony.jndi.provider.ldap.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LdapUrlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SCHEME = 1;
  /** RegularExpression Id. */
  int PRE_XTOKEN = 2;
  /** RegularExpression Id. */
  int SCOPE = 3;
  /** RegularExpression Id. */
  int COMMA = 4;
  /** RegularExpression Id. */
  int QUESTION_MARK = 5;
  /** RegularExpression Id. */
  int SLASH = 6;
  /** RegularExpression Id. */
  int PERCENT = 7;
  /** RegularExpression Id. */
  int COLON = 8;
  /** RegularExpression Id. */
  int PERIOD = 9;
  /** RegularExpression Id. */
  int EXCLAM_MARK = 10;
  /** RegularExpression Id. */
  int EQUAL = 11;
  /** RegularExpression Id. */
  int HEX_CHAR = 12;
  /** RegularExpression Id. */
  int NOHEX_CHAR = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int ZERO = 15;
  /** RegularExpression Id. */
  int CHAR = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SCHEME>",
    "<PRE_XTOKEN>",
    "<SCOPE>",
    "\",\"",
    "\"?\"",
    "\"/\"",
    "\"%\"",
    "\":\"",
    "\".\"",
    "\"!\"",
    "\"=\"",
    "<HEX_CHAR>",
    "<NOHEX_CHAR>",
    "<DIGIT>",
    "\"0\"",
    "<CHAR>",
    "\"\\n\"",
    "\"\\u0085\"",
  };

}
